files:
  - source: /po/cast-to-tv.pot
    translation: /po/%two_letters_code%.po
  - source: /po_addons/cast-to-tv-links-addon/cast-to-tv-links-addon.pot
    translation: /po_addons/cast-to-tv-links-addon/%two_letters_code%.po
